    <table width = "100%">
        <tr><td colspan = "2"><hr /></td>
            <td rowspan = "2" width = "33px" height = "38px">
                <a href = "index.htm" target="_top">
                <img src="Images/x.jpg" 
                width = "33px" height = "38px"
                alt="Image: Corporate image" /></a></td></tr>
        <tr><td><h5>01January2017 <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.<br></h5></td>
            <td><h5 style="text-align:right">Return to Homepage</h5></td></tr>
    </table>
